version: '3.3'

services:
  development:
    build: ./Client
    expose:
      - 3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_ROOT_DOMAIN: 'thebadsoftwareclub.net'
      REACT_APP_APP_DOMAIN: 'exampleapp'
      REACT_APP_API_DOMAIN: 'exampleapi'
      REACT_APP_AUTH_DOMAIN: 'exampleauth'
      REACT_APP_AWS_REGION: 'us-west-2'
      REACT_APP_AWS_USERPOOLID: 'tRduYkl8a'
      REACT_APP_AWS_USERPOOLCLIENTID: '76tj56t3vjtqb0g8p3b7hpajd6'
    ports:
      - 80:3000
    volumes:
      - ./Client/src:/usr/src/app/src
      - ./Client/public:/usr/src/app/public
    command: npm run start
    stdin_open: true
    tty: true
  production:
    build: ./Client
    depends_on:
      - development
    environment:
      REACT_APP_ROOT_DOMAIN: 'thebadsoftwareclub.net'
      REACT_APP_APP_DOMAIN: 'exampleapp'
      REACT_APP_API_DOMAIN: 'exampleapi'
      REACT_APP_AUTH_DOMAIN: 'exampleauth'
      REACT_APP_AWS_REGION: 'us-west-2'
      REACT_APP_AWS_USERPOOLID: 'tRduYkl8a'
      REACT_APP_AWS_USERPOOLCLIENTID: '76tj56t3vjtqb0g8p3b7hpajd6'
    volumes:
      - ./Client/src:/usr/src/app/src
      - ./Client/public:/usr/src/app/public
      - ./Client/build:/usr/src/app/build
    command: npm run build
