version: '3.3'

services:
  development:
    build: ./Client
    expose:
      - 3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_APP_URL: 'https://exampleapp.thebadsoftwareclub.net'
      REACT_APP_API_URL: 'https://exampleapi.thebadsoftwareclub.net'
      REACT_APP_AUTH_DOMAIN: 'exampleauth.thebadsoftwareclub.net'
      REACT_APP_AWS_REGION: 'us-west-2'
      REACT_APP_AWS_USERPOOLID: 'KecZiajyf'
      REACT_APP_AWS_USERPOOLCLIENTID: '2hbs3roftndbebt06jnjkev2g1'

    ports:
      - 80:3000
    volumes:
      - ./Client/src:/usr/src/app/src
      - ./Client/public:/usr/src/app/public
    command: npm run start
    stdin_open: true
    tty: true
  production:
    build: ./Client
    depends_on:
      - development
    environment:
      REACT_APP_APP_URL: 'https://exampleapp.thebadsoftwareclub.net'
      REACT_APP_API_URL: 'https://exampleapi.thebadsoftwareclub.net'
      REACT_APP_AUTH_DOMAIN: 'exampleauth.thebadsoftwareclub.net'
      REACT_APP_AWS_REGION: 'us-west-2'
      REACT_APP_AWS_USERPOOLID: 'KecZiajyf'
      REACT_APP_AWS_USERPOOLCLIENTID: '2hbs3roftndbebt06jnjkev2g1'

    volumes:
      - ./Client/src:/usr/src/app/src
      - ./Client/public:/usr/src/app/public
      - ./Client/build:/usr/src/app/build
    command: npm run build
