version: '3.3'

services:
  development:
    build: ./Client
    expose:
      - 3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_URL: 'http://localhost/'
    ports:
      - 80:3000
    volumes:
      - ./Client/src:/usr/src/app/src
    command: npm run start
    stdin_open: true
    tty: true
  production:
    build: ./Client
    depends_on:
      - development
    env_file:
      - ./.env.prod
    volumes:
      - ./Client/build:/usr/src/app/build
    command: npm run build