version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "example-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-159uve3khawhz"
s3_prefix = "example-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
